CREATE DATABASE IF NOT EXISTS bdmemoria;

USE bdmemoria;

CREATE TABLE usuarios (  
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  senha VARCHAR(50) NOT NULL,
  score INT(40) NOT NULL
);